### ISSUE TITLE
Skeleton Schematic Spawning without air

### ISSUE THREAD

**Issue by TekhnaeRaav** [TekhnaeRaav/Fossils#1]
Due to either my lack of knowledge or the inability of World Edit I am not able to get the skeleton schematics to spawn without blocks of air surrounding them.

If anyone has knowledge on the subject please tell.
If you want to address on the world edit problem I have created an issue on the subject in [Uberi/WorldEdit](https://github.com/Uberi/Minetest-WorldEdit/issues/155)

**Comment by slemonide** [comment]
well, you can replace air with stone

**Comment by TekhnaeRaav** [comment]
Thanks for the idea!
You might have the occasional problem where the schematic penetrates an open cave. But this will work nicely for now, thanks.

**Comment by slemonide** [comment]
Maybe playing around with force_placement parameter can be helpful. https://dev.minetest.net/minetest.place_schematic

**Comment by slemonide** [comment]
you can also save the volume replaced by the schematics somehow and then manually add back stone and ores

**Comment by TekhnaeRaav** [comment]
Fixed!
CasimirKaPazi's Schemtools mod did everything needed.
Thanks @CasimirKaPazi! Also thanks to @duane-r and @paramat for your individual mods!

**Comment by paramat** [comment]
WE is no good for creating schematics because it can't set per-node force-place or set probability on air.
For MTG we create schematics using Lua tables in https://github.com/minetest-mods/saveschems

**Comment by TekhnaeRaav** [comment]
Thanks for reminding me to close my world edit issue.
